// <auto-generated />
namespace AssetManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOrderDiscount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOrderDiscount));
        
        string IMigrationMetadata.Id => "201601070235293_AddOrderDiscount";
        
        string IMigrationMetadata.Source => null;
        
        string IMigrationMetadata.Target => Resources.GetString("Target");
    }
}
